#!/usr/bin/env python3
"""Regenerate the per-arm sbatch scripts from profiles.py.

The sbatch files are generated rather than hand-written so that the stage table
in their header, and the walltime they ask for, cannot drift away from the arm
definitions the runner actually uses. Edit profiles.py, rerun this, commit both.

    python nl2solidity/ablation/gen_sbatch.py
    python nl2solidity/ablation/gen_sbatch.py --account gts-myacct --partition cpu-large
    python nl2solidity/ablation/gen_sbatch.py --check     # CI: fail if stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import profiles  # noqa: E402

TEMPLATE = '''#!/bin/bash
#SBATCH --job-name={job}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --time={hours}:00:00
#SBATCH --array=1-{shards}%{shards}
#SBATCH --signal=B:TERM@300
#SBATCH --output=logs/{arm_lower}_%A_%a.out
#SBATCH --error=logs/{arm_lower}_%A_%a.err
#
# GENERATED by nl2solidity/ablation/gen_sbatch.py from profiles.py. Do not hand-edit:
# change the arm in profiles.py and regenerate, or the header below will lie.
#
# Ablation {arm}: {title}
# Adds over {prev}: {adds}
#
# Stages wired for this arm. Every feedback stage is *measured* on every arm, so
# all six carry the same metrics; "repair" marks the ones this arm may fix against.
{stage_block}
#
# The array runs {shards} independent shards of this arm. Shard k takes the seeds
# where (seed position % {shards}) == k, so the shards are disjoint by construction
# and no two tasks ever generate the same seed. Rerunning the identical
# submission resumes: completed seed directories are skipped.
#
# Submit from the repo root:   sbatch nl2solidity/ablation/pace/{arm_lower}.sbatch
# Override the shard count:    ABLATION_SHARDS=6 sbatch --array=1-6%6 nl2solidity/ablation/pace/{arm_lower}.sbatch
#
# Output: nl2solidity/dataset/ablation/{arm}/U###/

REPO="${{REPO:-${{SLURM_SUBMIT_DIR:-$PWD}}}}"
source "$REPO/nl2solidity/ablation/pace/common.sh"

run_arm {arm}
'''

# Generation stages: on or off for this arm.
GENERATION_KEYS = ("RAG_ENABLED", "MOE_ENABLED")

# Feedback stages. Under the default measure-all mode every one of these runs on
# every arm; what distinguishes an arm is which ones it may *repair* against.
FEEDBACK_KEYS = (
    "COMPILER_FEEDBACK_ENABLED",
    "KERNEL_FEEDBACK_ENABLED",
    "SECURITY_ANALYSIS_ENABLED",
    "SPEC_ALIGNMENT_ENABLED",
)


def _stage_block(arm) -> str:
    env = arm.resolved_env()
    lines = []
    for key in GENERATION_KEYS:
        lines.append(f"#   [{'on     ' if env[key] == 'true' else 'off    '}] {key}")
    for key in FEEDBACK_KEYS:
        # Owned by the arm -> repairs against it. Otherwise measured only.
        mark = "repair " if arm.env.get(key) == "true" else "measure"
        lines.append(f"#   [{mark}] {key}")
    return "\n".join(lines)

_PREV = {"A0": "nothing (this is the baseline)"}


def _previous(arm_id: str) -> str:
    if arm_id in _PREV:
        return _PREV[arm_id]
    idx = profiles.ARM_IDS.index(arm_id)
    return profiles.ARM_IDS[idx - 1]


def render(arm_id: str, account: str, partition: str, shards: int,
           cpus: int, mem: str) -> str:
    arm = profiles.get(arm_id)
    return TEMPLATE.format(
        job=f"abl-{arm_id.lower()}",
        account=account,
        partition=partition,
        cpus=cpus,
        mem=mem,
        hours=arm.hours,
        shards=shards,
        arm=arm_id,
        arm_lower=arm_id.lower(),
        title=arm.title,
        adds=arm.adds,
        prev=_previous(arm_id),
        stage_block=_stage_block(arm),
    )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--account", default="gts-CHANGEME", help="PACE charge account")
    parser.add_argument("--partition", default="cpu-small", help="PACE partition/queue")
    parser.add_argument("--shards", type=int, default=5,
                        help="instances per arm; the study calls for 4-6 (default 5)")
    parser.add_argument("--cpus", type=int, default=8, help="--cpus-per-task")
    parser.add_argument("--mem", default="16G", help="--mem")
    parser.add_argument("--out-dir", default=str(_HERE / "pace"))
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if any file on disk differs from the render")
    args = parser.parse_args(argv)

    if not 1 <= args.shards <= 32:
        print("Error: --shards must be in [1, 32]", file=sys.stderr)
        return 2

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    stale = []
    for arm_id in profiles.ARM_IDS:
        text = render(arm_id, args.account, args.partition, args.shards,
                      args.cpus, args.mem)
        path = out_dir / f"{arm_id.lower()}.sbatch"
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(path.name)
            continue
        path.write_text(text)
        path.chmod(0o755)
        print(f"wrote {path}")

    if args.check:
        if stale:
            print("stale sbatch files (rerun gen_sbatch.py): " + ", ".join(stale),
                  file=sys.stderr)
            return 1
        print(f"all {len(profiles.ARM_IDS)} sbatch files match profiles.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
